openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
paths:
  /api/compare/members:
    get:
      deprecated: false
      tags:
      - COMPARE-CONTROLLER
      parameters:
      - name: page
        in: query
        required: true
        schema:
          type: integer
      - name: size
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/com.c102.ourotest.dto.MemberResponse'
      x-ouroboros-id: 16bd6997-4679-4781-a468-e531b28dadc5
      x-ouroboros-progress: completed
      x-ouroboros-tag: none
      x-ouroboros-diff: none
    post:
      deprecated: false
      tags:
      - COMPARE-CONTROLLER
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/com.c102.ourotest.dto.CreateMemberDTO'
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                type: string
      x-ouroboros-id: b1c75006-f0de-41eb-a966-7591721188dd
      x-ouroboros-progress: completed
      x-ouroboros-tag: none
      x-ouroboros-diff: none
      x-ouroboros-response: use
  /api/compare/members/{memberId}:
    get:
      deprecated: false
      tags:
      - COMPARE-CONTROLLER
      parameters:
      - name: memberId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/com.c102.ourotest.dto.MemberResponse'
      x-ouroboros-id: 8b3868e9-2689-4c20-8c2e-7256d9b101d6
      x-ouroboros-progress: completed
      x-ouroboros-tag: none
      x-ouroboros-diff: none
    delete:
      deprecated: false
      tags:
      - COMPARE-CONTROLLER
      parameters:
      - name: memberId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/com.c102.ourotest.dto.MemberResponse'
      x-ouroboros-id: fb85b2e3-a425-4ddf-a794-83f3f93e03ec
      x-ouroboros-progress: completed
      x-ouroboros-tag: none
      x-ouroboros-diff: none
  /api/chat/{roomId}/send:
    post:
      deprecated: false
      tags:
      - chat-controller
      parameters:
      - name: roomId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/com.c102.ourotest.chat.dto.ChatMessage'
      responses:
        '200':
          description: OK
      x-ouroboros-id: bec4d93e-d7c6-4835-9d1a-1db113714eab
      x-ouroboros-progress: completed
      x-ouroboros-tag: none
      x-ouroboros-diff: endpoint
  /api/compare/members/analyze/{memberId}:
    get:
      deprecated: false
      tags:
      - compare-controller
      parameters:
      - name: memberId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/com.c102.ourotest.dto.MemberResponse'
      x-ouroboros-id: edb3d532-1180-4a89-8d23-b6931d407dbf
      x-ouroboros-progress: completed
      x-ouroboros-tag: none
      x-ouroboros-diff: endpoint
      x-ouroboros-response: use
components:
  schemas:
    com.c102.ourotest.dto.CreateMemberDTO:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
        age:
          type: integer
          format: int32
        phone:
          type: string
    com.c102.ourotest.chat.dto.ChatMessage:
      type: object
      properties:
        roomId:
          type: string
        sender:
          type: string
        content:
          type: string
        type:
          type: string
        sentAt:
          type: string
          format: date-time
    com.c102.ourotest.dto.MemberResponse:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        age:
          type: integer
          format: int32
        phone:
          type: string
servers:
- url: http://localhost:8080
  description: Generated server url
