openapi: 3.0.0
info:
  title: 샘플 API 테스트
  version: 1.0.0
  description: Redoc 코드 스니펫 테스트용
paths:
  /api/users/{userId}:
    get:
      summary: 사용자 정보 조회
      description: ID를 사용하여 특정 사용자의 정보를 가져옵니다.
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum: [json, xml]
            default: json
      responses:
        '200':
          description: 성공적인 응답
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                SampleUser:
                  value:
                    id: 1
                    name: '홍길동'
                    email: 'gildong@example.com'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string